# Semgrep configuration to avoid remote timeout issues
# This configuration uses local rules instead of downloading from semgrep.dev

rules:
  - id: python-print-statement
    pattern: print(...)
    message: Found print statement. Consider using logging instead.
    languages: [python]
    severity: INFO
    
  - id: python-bare-except
    pattern: |
      try:
        ...
      except:
        ...
    message: Avoid bare except clauses. Catch specific exceptions instead.
    languages: [python]
    severity: WARNING
    
  - id: python-assert-used
    pattern: assert ...
    message: Avoid using assert statements in production code
    languages: [python]
    severity: INFO

  - id: javascript-console-log
    pattern: console.log(...)
    message: Found console.log statement. Consider using proper logging.
    languages: [javascript, typescript]
    severity: INFO

  - id: hardcoded-secret
    pattern-either:
      - pattern: password = "..."
      - pattern: api_key = "..."
      - pattern: secret = "..."
      - pattern: token = "..."
    message: Possible hardcoded secret found
    languages: [python, javascript, typescript]
    severity: ERROR
